/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module digital_wrapper(clk, rst_n, start, comp_in, sclk, cs_n, mosi, miso, bp9, bp8, bp7, bp6, bp5, bp4, bp3, bp2, bp1, bp0, bn9, bn8, bn7
, bn6, bn5, bn4, bn3, bn2, bn1, bn0, bist_en);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input comp_in;
  wire comp_in;
  input sclk;
  wire sclk;
  input cs_n;
  wire cs_n;
  input mosi;
  wire mosi;
  output miso;
  wire miso;
  output bp9;
  wire bp9;
  output bp8;
  wire bp8;
  output bp7;
  wire bp7;
  output bp6;
  wire bp6;
  output bp5;
  wire bp5;
  output bp4;
  wire bp4;
  output bp3;
  wire bp3;
  output bp2;
  wire bp2;
  output bp1;
  wire bp1;
  output bp0;
  wire bp0;
  output bn9;
  wire bn9;
  output bn8;
  wire bn8;
  output bn7;
  wire bn7;
  output bn6;
  wire bn6;
  output bn5;
  wire bn5;
  output bn4;
  wire bn4;
  output bn3;
  wire bn3;
  output bn2;
  wire bn2;
  output bn1;
  wire bn1;
  output bn0;
  wire bn0;
  output bist_en;
  wire bist_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire \cal_result[0] ;
  wire \cal_result[1] ;
  wire \cal_result[2] ;
  wire \cal_result[3] ;
  wire \cal_result[4] ;
  wire \cal_result[5] ;
  wire \cal_result[6] ;
  wire \cal_result[7] ;
  wire \cal_result[8] ;
  wire \cal_result[9] ;
  wire cal_valid;
  wire \offset[0] ;
  wire \offset[1] ;
  wire \offset[2] ;
  wire \offset[3] ;
  wire \offset[4] ;
  wire \offset[5] ;
  wire \offset[6] ;
  wire \offset[7] ;
  wire \offset[8] ;
  wire \offset[9] ;
  wire \sar_result[0] ;
  wire \sar_result[1] ;
  wire \sar_result[2] ;
  wire \sar_result[3] ;
  wire \sar_result[4] ;
  wire \sar_result[5] ;
  wire \sar_result[6] ;
  wire \sar_result[7] ;
  wire \sar_result[8] ;
  wire \sar_result[9] ;
  wire sar_valid;
  wire \u_sar.bit_idx[0] ;
  wire \u_sar.bit_idx[1] ;
  wire \u_sar.bit_idx[2] ;
  wire \u_sar.bit_idx[3] ;
  wire \u_sar.count[0] ;
  wire \u_sar.count[1] ;
  wire \u_sar.count[2] ;
  wire \u_sar.count[3] ;
  wire \u_sar.count[4] ;
  wire \u_sar.count[5] ;
  wire \u_sar.count[6] ;
  wire \u_sar.count[7] ;
  wire \u_sar.state[0] ;
  wire \u_sar.state[1] ;
  wire \u_sar.state[2] ;
  wire \u_sar.state[3] ;
  wire \u_sar.state[4] ;
  wire \u_sar.state[5] ;
  wire \u_spi.bit_cnt[0] ;
  wire \u_spi.bit_cnt[1] ;
  wire \u_spi.bit_cnt[2] ;
  wire \u_spi.bit_cnt[3] ;
  wire \u_spi.bit_cnt[4] ;
  wire \u_spi.bit_cnt[5] ;
  wire \u_spi.bit_cnt[6] ;
  wire \u_spi.bit_cnt[7] ;
  wire \u_spi.cs_n_prev ;
  wire \u_spi.data_latch[0] ;
  wire \u_spi.data_latch[1] ;
  wire \u_spi.data_latch[2] ;
  wire \u_spi.data_latch[3] ;
  wire \u_spi.data_latch[4] ;
  wire \u_spi.data_latch[5] ;
  wire \u_spi.data_latch[6] ;
  wire \u_spi.data_latch[7] ;
  wire \u_spi.data_latch[8] ;
  wire \u_spi.data_latch[9] ;
  wire \u_spi.mosi_reg[0] ;
  wire \u_spi.mosi_reg[1] ;
  wire \u_spi.mosi_reg[2] ;
  wire \u_spi.mosi_reg[3] ;
  wire \u_spi.mosi_reg[4] ;
  wire \u_spi.mosi_reg[5] ;
  wire \u_spi.mosi_reg[6] ;
  wire \u_spi.mosi_reg[7] ;
  wire \u_spi.mosi_reg[8] ;
  wire \u_spi.mosi_reg[9] ;
  wire \u_spi.shift_reg[0] ;
  wire \u_spi.shift_reg[1] ;
  wire \u_spi.shift_reg[2] ;
  wire \u_spi.shift_reg[3] ;
  wire \u_spi.shift_reg[4] ;
  wire \u_spi.shift_reg[5] ;
  wire \u_spi.shift_reg[6] ;
  wire \u_spi.shift_reg[7] ;
  wire \u_spi.shift_reg[8] ;
  wire \u_spi.shift_reg[9] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _324_ (
    .I(cs_n),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _325_ (
    .I(\u_sar.state[2] ),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _326_ (
    .I(\u_sar.count[1] ),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _327_ (
    .I(\u_sar.count[0] ),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _328_ (
    .I(\u_sar.count[4] ),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _329_ (
    .I(\u_sar.count[6] ),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _330_ (
    .I(\u_sar.state[1] ),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _331_ (
    .I(\u_sar.bit_idx[1] ),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _332_ (
    .I(\u_sar.bit_idx[3] ),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _333_ (
    .I(comp_in),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _334_ (
    .I(start),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _335_ (
    .I(\u_sar.state[4] ),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _336_ (
    .I(\sar_result[8] ),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _337_ (
    .I(\sar_result[6] ),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _338_ (
    .I(\sar_result[5] ),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _339_ (
    .I(\sar_result[4] ),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _340_ (
    .I(\sar_result[0] ),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _341_ (
    .I(bn0),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _342_ (
    .I(bp0),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _343_ (
    .A1(\u_sar.count[4] ),
    .A2(\u_sar.count[7] ),
    .A3(\u_sar.count[6] ),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _344_ (
    .A1(_097_),
    .A2(\u_sar.count[3] ),
    .A3(\u_sar.count[2] ),
    .A4(\u_sar.count[5] ),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _345_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _346_ (
    .A1(\u_sar.count[0] ),
    .A2(_116_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _347_ (
    .I(_117_),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _348_ (
    .A1(_096_),
    .A2(_118_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _349_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(\u_sar.bit_idx[0] ),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _350_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(\u_sar.bit_idx[0] ),
    .A3(\u_sar.bit_idx[2] ),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _351_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(\u_sar.bit_idx[0] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _352_ (
    .A1(_103_),
    .A2(_120_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _353_ (
    .A1(\u_sar.state[1] ),
    .A2(_121_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _354_ (
    .I(_123_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _355_ (
    .A1(\u_sar.state[0] ),
    .A2(start),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _356_ (
    .A1(_098_),
    .A2(_116_),
    .B(\u_sar.state[3] ),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _357_ (
    .A1(_124_),
    .A2(_125_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _358_ (
    .A1(\u_sar.count[0] ),
    .A2(\u_sar.state[3] ),
    .A3(_114_),
    .A4(_115_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _359_ (
    .A1(_096_),
    .A2(_117_),
    .B1(_121_),
    .B2(_101_),
    .C(_126_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _360_ (
    .A1(\u_sar.state[0] ),
    .A2(_105_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _361_ (
    .A1(_106_),
    .A2(_127_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _362_ (
    .A1(_095_),
    .A2(\u_spi.shift_reg[9] ),
    .Z(miso)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _363_ (
    .A1(\u_spi.bit_cnt[2] ),
    .A2(\u_spi.bit_cnt[1] ),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _364_ (
    .A1(cs_n),
    .A2(\u_spi.cs_n_prev ),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _365_ (
    .A1(\u_spi.bit_cnt[7] ),
    .A2(cs_n),
    .A3(\u_spi.bit_cnt[4] ),
    .A4(\u_spi.cs_n_prev ),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _366_ (
    .A1(\u_spi.bit_cnt[3] ),
    .A2(\u_spi.bit_cnt[0] ),
    .A3(_128_),
    .A4(_130_),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _367_ (
    .A1(\u_spi.bit_cnt[6] ),
    .A2(\u_spi.bit_cnt[5] ),
    .A3(_131_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _368_ (
    .I0(\offset[6] ),
    .I1(\u_spi.mosi_reg[6] ),
    .S(_132_),
    .Z(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _369_ (
    .I0(\offset[7] ),
    .I1(\u_spi.mosi_reg[7] ),
    .S(_132_),
    .Z(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _370_ (
    .I0(\offset[8] ),
    .I1(\u_spi.mosi_reg[8] ),
    .S(_132_),
    .Z(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _371_ (
    .I0(\offset[9] ),
    .I1(\u_spi.mosi_reg[9] ),
    .S(_132_),
    .Z(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _372_ (
    .I0(\u_spi.mosi_reg[0] ),
    .I1(mosi),
    .S(_129_),
    .Z(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _373_ (
    .I0(\u_spi.mosi_reg[1] ),
    .I1(\u_spi.mosi_reg[0] ),
    .S(_129_),
    .Z(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _374_ (
    .I0(\u_spi.mosi_reg[2] ),
    .I1(\u_spi.mosi_reg[1] ),
    .S(_129_),
    .Z(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _375_ (
    .I0(\u_spi.mosi_reg[3] ),
    .I1(\u_spi.mosi_reg[2] ),
    .S(_129_),
    .Z(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _376_ (
    .I0(\u_spi.mosi_reg[4] ),
    .I1(\u_spi.mosi_reg[3] ),
    .S(_129_),
    .Z(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _377_ (
    .I0(\u_spi.mosi_reg[5] ),
    .I1(\u_spi.mosi_reg[4] ),
    .S(_129_),
    .Z(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _378_ (
    .I0(\u_spi.mosi_reg[6] ),
    .I1(\u_spi.mosi_reg[5] ),
    .S(_129_),
    .Z(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _379_ (
    .I0(\u_spi.mosi_reg[7] ),
    .I1(\u_spi.mosi_reg[6] ),
    .S(_129_),
    .Z(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _380_ (
    .I0(\u_spi.mosi_reg[8] ),
    .I1(\u_spi.mosi_reg[7] ),
    .S(_129_),
    .Z(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _381_ (
    .I0(\u_spi.mosi_reg[9] ),
    .I1(\u_spi.mosi_reg[8] ),
    .S(_129_),
    .Z(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _382_ (
    .A1(\u_spi.bit_cnt[0] ),
    .A2(_129_),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _383_ (
    .A1(_095_),
    .A2(\u_spi.bit_cnt[0] ),
    .B(_133_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _384_ (
    .A1(_095_),
    .A2(\u_spi.bit_cnt[1] ),
    .A3(\u_spi.bit_cnt[0] ),
    .Z(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _385_ (
    .A1(_095_),
    .A2(\u_spi.cs_n_prev ),
    .Z(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _386_ (
    .A1(_095_),
    .A2(\u_spi.bit_cnt[0] ),
    .B(\u_spi.bit_cnt[1] ),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _387_ (
    .A1(_134_),
    .A2(_135_),
    .A3(_136_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _388_ (
    .A1(\u_spi.bit_cnt[2] ),
    .A2(_134_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _389_ (
    .A1(_135_),
    .A2(_137_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _390_ (
    .A1(\u_spi.bit_cnt[2] ),
    .A2(_134_),
    .B(\u_spi.bit_cnt[3] ),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _391_ (
    .A1(\u_spi.bit_cnt[3] ),
    .A2(\u_spi.bit_cnt[2] ),
    .A3(_134_),
    .Z(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _392_ (
    .A1(_135_),
    .A2(_138_),
    .A3(_139_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _393_ (
    .A1(\u_spi.bit_cnt[4] ),
    .A2(_139_),
    .B(_135_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _394_ (
    .A1(\u_spi.bit_cnt[4] ),
    .A2(_139_),
    .B(_140_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _395_ (
    .I(_141_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _396_ (
    .A1(\u_spi.bit_cnt[4] ),
    .A2(_139_),
    .B(\u_spi.bit_cnt[5] ),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _397_ (
    .A1(\u_spi.bit_cnt[5] ),
    .A2(\u_spi.bit_cnt[4] ),
    .A3(_139_),
    .Z(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _398_ (
    .A1(_135_),
    .A2(_142_),
    .A3(_143_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _399_ (
    .A1(\u_spi.bit_cnt[6] ),
    .A2(_143_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _400_ (
    .A1(\u_spi.bit_cnt[6] ),
    .A2(_143_),
    .Z(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _401_ (
    .A1(_135_),
    .A2(_144_),
    .A3(_145_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _402_ (
    .A1(\u_spi.bit_cnt[7] ),
    .A2(_145_),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _403_ (
    .A1(_135_),
    .A2(_146_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _404_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[1] ),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _405_ (
    .A1(\u_spi.shift_reg[0] ),
    .A2(_129_),
    .B1(_135_),
    .B2(\u_spi.data_latch[1] ),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _406_ (
    .A1(_147_),
    .A2(_148_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _407_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[2] ),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _408_ (
    .A1(\u_spi.shift_reg[1] ),
    .A2(_129_),
    .B1(_135_),
    .B2(\u_spi.data_latch[2] ),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _409_ (
    .A1(_149_),
    .A2(_150_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _410_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[3] ),
    .ZN(_151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _411_ (
    .A1(\u_spi.shift_reg[2] ),
    .A2(_129_),
    .B1(_135_),
    .B2(\u_spi.data_latch[3] ),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _412_ (
    .A1(_151_),
    .A2(_152_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _413_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[4] ),
    .ZN(_153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _414_ (
    .A1(\u_spi.shift_reg[3] ),
    .A2(_129_),
    .B1(_135_),
    .B2(\u_spi.data_latch[4] ),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _415_ (
    .A1(_153_),
    .A2(_154_),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _416_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[5] ),
    .B1(_129_),
    .B2(\u_spi.shift_reg[4] ),
    .C1(_135_),
    .C2(\u_spi.data_latch[5] ),
    .ZN(_155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _417_ (
    .I(_155_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _418_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[6] ),
    .B1(_129_),
    .B2(\u_spi.shift_reg[5] ),
    .C1(_135_),
    .C2(\u_spi.data_latch[6] ),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _419_ (
    .I(_156_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _420_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[7] ),
    .B1(_129_),
    .B2(\u_spi.shift_reg[6] ),
    .C1(_135_),
    .C2(\u_spi.data_latch[7] ),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _421_ (
    .I(_157_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _422_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[8] ),
    .B1(_129_),
    .B2(\u_spi.shift_reg[7] ),
    .C1(_135_),
    .C2(\u_spi.data_latch[8] ),
    .ZN(_158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _423_ (
    .I(_158_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _424_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[9] ),
    .B1(_129_),
    .B2(\u_spi.shift_reg[8] ),
    .C1(_135_),
    .C2(\u_spi.data_latch[9] ),
    .ZN(_159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _425_ (
    .I(_159_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _426_ (
    .A1(cs_n),
    .A2(\u_spi.shift_reg[0] ),
    .B1(_135_),
    .B2(\u_spi.data_latch[0] ),
    .ZN(_160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _427_ (
    .I(_160_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _428_ (
    .A1(\u_sar.state[1] ),
    .A2(\u_sar.state[0] ),
    .B(_127_),
    .ZN(_161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _429_ (
    .A1(\u_sar.state[1] ),
    .A2(\u_sar.state[0] ),
    .B(_123_),
    .C(_127_),
    .ZN(_162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _430_ (
    .A1(\u_sar.state[3] ),
    .A2(_123_),
    .A3(_127_),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _431_ (
    .A1(_162_),
    .A2(_163_),
    .Z(_164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _432_ (
    .A1(\u_sar.state[1] ),
    .A2(_164_),
    .ZN(_165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _433_ (
    .A1(_113_),
    .A2(_165_),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _434_ (
    .A1(_102_),
    .A2(\u_sar.bit_idx[0] ),
    .ZN(_166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _435_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(\u_sar.bit_idx[2] ),
    .A3(_166_),
    .ZN(_167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _436_ (
    .I(_167_),
    .ZN(_168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _437_ (
    .A1(comp_in),
    .A2(_164_),
    .ZN(_169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _438_ (
    .A1(_167_),
    .A2(_169_),
    .B(bp1),
    .ZN(_170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _439_ (
    .A1(_165_),
    .A2(_170_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _440_ (
    .A1(\u_sar.bit_idx[2] ),
    .A2(_119_),
    .Z(_171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _441_ (
    .A1(_102_),
    .A2(\u_sar.bit_idx[0] ),
    .ZN(_172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _442_ (
    .A1(_102_),
    .A2(\u_sar.bit_idx[0] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _443_ (
    .A1(_169_),
    .A2(_173_),
    .B(bp2),
    .ZN(_174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _444_ (
    .A1(_165_),
    .A2(_174_),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _445_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(\u_sar.bit_idx[0] ),
    .ZN(_175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _446_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_171_),
    .A3(_175_),
    .ZN(_176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _447_ (
    .A1(_169_),
    .A2(_176_),
    .B(bp3),
    .ZN(_177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _448_ (
    .A1(_165_),
    .A2(_177_),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _449_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_120_),
    .ZN(_178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _450_ (
    .A1(_119_),
    .A2(_178_),
    .Z(_179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _451_ (
    .A1(_119_),
    .A2(_178_),
    .ZN(_180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _452_ (
    .A1(_169_),
    .A2(_179_),
    .B(bp4),
    .ZN(_181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _453_ (
    .A1(_165_),
    .A2(_181_),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _454_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_120_),
    .Z(_182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _455_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_120_),
    .ZN(_183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _456_ (
    .A1(_103_),
    .A2(_120_),
    .Z(_184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _457_ (
    .I(_184_),
    .ZN(_185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _458_ (
    .A1(_171_),
    .A2(_184_),
    .Z(_186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _459_ (
    .A1(_171_),
    .A2(_184_),
    .ZN(_187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _460_ (
    .A1(_166_),
    .A2(_187_),
    .ZN(_188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _461_ (
    .A1(_102_),
    .A2(\u_sar.bit_idx[0] ),
    .A3(_186_),
    .ZN(_189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _462_ (
    .A1(_169_),
    .A2(_188_),
    .B(bp5),
    .ZN(_190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _463_ (
    .A1(_165_),
    .A2(_190_),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _464_ (
    .A1(_172_),
    .A2(_186_),
    .Z(_191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _465_ (
    .A1(_172_),
    .A2(_186_),
    .ZN(_192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _466_ (
    .A1(_169_),
    .A2(_191_),
    .B(bp6),
    .ZN(_193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _467_ (
    .A1(_165_),
    .A2(_193_),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _468_ (
    .A1(_175_),
    .A2(_187_),
    .ZN(_194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _469_ (
    .A1(_169_),
    .A2(_194_),
    .B(bp7),
    .ZN(_195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _470_ (
    .A1(_165_),
    .A2(_195_),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _471_ (
    .A1(_169_),
    .A2(_182_),
    .B(bp8),
    .ZN(_196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _472_ (
    .A1(_165_),
    .A2(_196_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _473_ (
    .A1(_103_),
    .A2(\u_sar.bit_idx[2] ),
    .A3(_166_),
    .ZN(_197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _474_ (
    .A1(_103_),
    .A2(\u_sar.bit_idx[2] ),
    .A3(_166_),
    .Z(_198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _475_ (
    .A1(_169_),
    .A2(_197_),
    .B(bp9),
    .ZN(_199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _476_ (
    .A1(_165_),
    .A2(_199_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _477_ (
    .A1(_112_),
    .A2(_165_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _478_ (
    .A1(_104_),
    .A2(_164_),
    .ZN(_200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _479_ (
    .A1(_167_),
    .A2(_200_),
    .B(bn1),
    .ZN(_201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _480_ (
    .A1(_165_),
    .A2(_201_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _481_ (
    .A1(_173_),
    .A2(_200_),
    .B(bn2),
    .ZN(_202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _482_ (
    .A1(_165_),
    .A2(_202_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _483_ (
    .A1(_176_),
    .A2(_200_),
    .B(bn3),
    .ZN(_203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _484_ (
    .A1(_165_),
    .A2(_203_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _485_ (
    .A1(_179_),
    .A2(_200_),
    .B(bn4),
    .ZN(_204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _486_ (
    .A1(_165_),
    .A2(_204_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _487_ (
    .A1(_188_),
    .A2(_200_),
    .B(bn5),
    .ZN(_205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _488_ (
    .A1(_165_),
    .A2(_205_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _489_ (
    .A1(_191_),
    .A2(_200_),
    .B(bn6),
    .ZN(_206_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _490_ (
    .A1(_165_),
    .A2(_206_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _491_ (
    .A1(_194_),
    .A2(_200_),
    .B(bn7),
    .ZN(_207_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _492_ (
    .A1(_165_),
    .A2(_207_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _493_ (
    .A1(_182_),
    .A2(_200_),
    .B(bn8),
    .ZN(_208_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _494_ (
    .A1(_165_),
    .A2(_208_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _495_ (
    .A1(_197_),
    .A2(_200_),
    .B(bn9),
    .ZN(_209_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _496_ (
    .A1(_165_),
    .A2(_209_),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _497_ (
    .A1(\u_sar.state[1] ),
    .A2(_122_),
    .B(_161_),
    .ZN(_210_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _498_ (
    .A1(\u_sar.state[0] ),
    .A2(_105_),
    .B(_101_),
    .ZN(_211_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _499_ (
    .A1(\u_sar.state[1] ),
    .A2(_127_),
    .ZN(_212_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _500_ (
    .A1(comp_in),
    .A2(_211_),
    .ZN(_213_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _501_ (
    .A1(_111_),
    .A2(_210_),
    .B1(_213_),
    .B2(_122_),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _502_ (
    .A1(\u_sar.bit_idx[2] ),
    .A2(_104_),
    .A3(_166_),
    .ZN(_214_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _503_ (
    .A1(\sar_result[1] ),
    .A2(_161_),
    .ZN(_215_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _504_ (
    .A1(\sar_result[1] ),
    .A2(_168_),
    .B1(_184_),
    .B2(_214_),
    .ZN(_216_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _505_ (
    .A1(_212_),
    .A2(_216_),
    .B(_215_),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _506_ (
    .A1(_101_),
    .A2(_173_),
    .ZN(_217_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _507_ (
    .A1(_161_),
    .A2(_217_),
    .B(\sar_result[2] ),
    .ZN(_218_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _508_ (
    .A1(comp_in),
    .A2(_122_),
    .A3(_173_),
    .A4(_211_),
    .ZN(_219_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _509_ (
    .A1(_218_),
    .A2(_219_),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _510_ (
    .I0(\sar_result[3] ),
    .I1(comp_in),
    .S(_176_),
    .Z(_220_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _511_ (
    .A1(\sar_result[3] ),
    .A2(_161_),
    .B1(_211_),
    .B2(_220_),
    .ZN(_221_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _512_ (
    .I(_221_),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _513_ (
    .A1(\u_sar.state[1] ),
    .A2(_180_),
    .B(_161_),
    .ZN(_222_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _514_ (
    .A1(_180_),
    .A2(_213_),
    .B1(_222_),
    .B2(_110_),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _515_ (
    .A1(\u_sar.state[1] ),
    .A2(_189_),
    .B(_161_),
    .ZN(_223_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _516_ (
    .A1(_189_),
    .A2(_213_),
    .B1(_223_),
    .B2(_109_),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _517_ (
    .A1(\u_sar.state[1] ),
    .A2(_192_),
    .B(_161_),
    .ZN(_224_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _518_ (
    .A1(_121_),
    .A2(_192_),
    .A3(_213_),
    .B1(_224_),
    .B2(_108_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _519_ (
    .I0(\sar_result[7] ),
    .I1(comp_in),
    .S(_194_),
    .Z(_225_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _520_ (
    .A1(\sar_result[7] ),
    .A2(_161_),
    .B1(_211_),
    .B2(_225_),
    .ZN(_226_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _521_ (
    .I(_226_),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _522_ (
    .A1(\u_sar.state[1] ),
    .A2(_183_),
    .B(_161_),
    .ZN(_227_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _523_ (
    .A1(_183_),
    .A2(_213_),
    .B1(_227_),
    .B2(_107_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _524_ (
    .A1(\sar_result[9] ),
    .A2(_198_),
    .B1(_214_),
    .B2(_185_),
    .ZN(_228_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _525_ (
    .A1(\sar_result[9] ),
    .A2(_161_),
    .ZN(_229_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _526_ (
    .A1(_212_),
    .A2(_228_),
    .B(_229_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _527_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(_212_),
    .ZN(_230_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _528_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(_162_),
    .B(_230_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _529_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(_162_),
    .ZN(_231_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _530_ (
    .A1(\u_sar.bit_idx[1] ),
    .A2(\u_sar.bit_idx[0] ),
    .Z(_232_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _531_ (
    .A1(_121_),
    .A2(_212_),
    .A3(_232_),
    .B(_231_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _532_ (
    .A1(_122_),
    .A2(_171_),
    .A3(_211_),
    .ZN(_233_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _533_ (
    .A1(\u_sar.bit_idx[2] ),
    .A2(_162_),
    .ZN(_234_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _534_ (
    .A1(_233_),
    .A2(_234_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _535_ (
    .A1(_103_),
    .A2(_162_),
    .B1(_184_),
    .B2(_211_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _536_ (
    .A1(\u_sar.state[2] ),
    .A2(\u_sar.state[3] ),
    .Z(_235_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _537_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_235_),
    .ZN(_236_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _538_ (
    .A1(_162_),
    .A2(_236_),
    .ZN(_237_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _539_ (
    .A1(_162_),
    .A2(_236_),
    .B(_098_),
    .ZN(_238_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _540_ (
    .A1(\u_sar.count[0] ),
    .A2(_237_),
    .ZN(_239_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _541_ (
    .A1(\u_sar.state[2] ),
    .A2(_118_),
    .B1(_162_),
    .B2(_236_),
    .C(\u_sar.state[3] ),
    .ZN(_240_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _542_ (
    .A1(_238_),
    .A2(_239_),
    .A3(_240_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _543_ (
    .A1(\u_sar.count[1] ),
    .A2(_238_),
    .ZN(_241_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _544_ (
    .A1(\u_sar.count[1] ),
    .A2(_238_),
    .Z(_242_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _545_ (
    .A1(_240_),
    .A2(_241_),
    .A3(_242_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _546_ (
    .A1(_096_),
    .A2(_125_),
    .A3(_237_),
    .ZN(_243_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _547_ (
    .A1(\u_sar.count[2] ),
    .A2(_242_),
    .B(_243_),
    .ZN(_244_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _548_ (
    .A1(\u_sar.count[2] ),
    .A2(_242_),
    .B(_244_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _549_ (
    .A1(\u_sar.count[1] ),
    .A2(\u_sar.count[0] ),
    .A3(\u_sar.count[3] ),
    .A4(\u_sar.count[2] ),
    .ZN(_245_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _550_ (
    .A1(_235_),
    .A2(_245_),
    .ZN(_246_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _551_ (
    .A1(_237_),
    .A2(_246_),
    .ZN(_247_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _552_ (
    .A1(\u_sar.count[2] ),
    .A2(_242_),
    .B(\u_sar.count[3] ),
    .ZN(_248_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _553_ (
    .A1(_237_),
    .A2(_246_),
    .B(_248_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _554_ (
    .A1(\u_sar.count[4] ),
    .A2(_247_),
    .ZN(_249_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _555_ (
    .A1(\u_sar.count[4] ),
    .A2(_236_),
    .A3(_245_),
    .B(_249_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _556_ (
    .A1(_099_),
    .A2(_245_),
    .ZN(_250_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _557_ (
    .A1(_237_),
    .A2(_250_),
    .B(\u_sar.count[5] ),
    .ZN(_251_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _558_ (
    .A1(\u_sar.count[5] ),
    .A2(_237_),
    .A3(_250_),
    .ZN(_252_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _559_ (
    .A1(_162_),
    .A2(_235_),
    .B(_252_),
    .ZN(_253_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _560_ (
    .A1(_251_),
    .A2(_253_),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _561_ (
    .A1(\u_sar.count[5] ),
    .A2(\u_sar.count[6] ),
    .A3(_250_),
    .ZN(_254_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _562_ (
    .A1(_235_),
    .A2(_254_),
    .ZN(_255_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _563_ (
    .A1(_237_),
    .A2(_255_),
    .ZN(_256_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _564_ (
    .A1(_100_),
    .A2(_252_),
    .B1(_255_),
    .B2(_237_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _565_ (
    .A1(\u_sar.count[7] ),
    .A2(_256_),
    .ZN(_257_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _566_ (
    .A1(\u_sar.count[7] ),
    .A2(_236_),
    .A3(_254_),
    .B(_257_),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _567_ (
    .A1(\offset[0] ),
    .A2(\sar_result[0] ),
    .Z(_258_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _568_ (
    .A1(\offset[0] ),
    .A2(\sar_result[0] ),
    .ZN(_259_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _569_ (
    .A1(\offset[0] ),
    .A2(_111_),
    .Z(_260_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _570_ (
    .A1(\offset[9] ),
    .A2(\sar_result[9] ),
    .Z(_261_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _571_ (
    .A1(\offset[8] ),
    .A2(\sar_result[8] ),
    .ZN(_262_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _572_ (
    .A1(\offset[1] ),
    .A2(\sar_result[1] ),
    .Z(_263_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _573_ (
    .A1(\offset[1] ),
    .A2(\sar_result[1] ),
    .ZN(_264_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _574_ (
    .A1(\offset[1] ),
    .A2(\sar_result[1] ),
    .ZN(_265_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _575_ (
    .A1(\offset[1] ),
    .A2(\sar_result[1] ),
    .Z(_266_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _576_ (
    .A1(_258_),
    .A2(_266_),
    .B(_263_),
    .ZN(_267_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _577_ (
    .A1(_259_),
    .A2(_265_),
    .B(_264_),
    .ZN(_268_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _578_ (
    .A1(\offset[2] ),
    .A2(\sar_result[2] ),
    .Z(_269_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _579_ (
    .A1(\offset[2] ),
    .A2(\sar_result[2] ),
    .Z(_270_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _580_ (
    .A1(\offset[3] ),
    .A2(\sar_result[3] ),
    .ZN(_271_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _581_ (
    .A1(\offset[3] ),
    .A2(\sar_result[3] ),
    .Z(_272_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _582_ (
    .A1(_270_),
    .A2(_272_),
    .Z(_273_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _583_ (
    .A1(_270_),
    .A2(_272_),
    .ZN(_274_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _584_ (
    .A1(\offset[3] ),
    .A2(\sar_result[3] ),
    .B(\offset[2] ),
    .C(\sar_result[2] ),
    .ZN(_275_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _585_ (
    .A1(_271_),
    .A2(_275_),
    .ZN(_276_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _586_ (
    .A1(_268_),
    .A2(_273_),
    .B(_276_),
    .ZN(_277_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _587_ (
    .A1(_267_),
    .A2(_274_),
    .B(_275_),
    .C(_271_),
    .ZN(_278_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _588_ (
    .A1(\offset[6] ),
    .A2(\sar_result[6] ),
    .Z(_279_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _589_ (
    .A1(\offset[6] ),
    .A2(\sar_result[6] ),
    .Z(_280_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _590_ (
    .A1(\offset[7] ),
    .A2(\sar_result[7] ),
    .ZN(_281_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _591_ (
    .A1(\offset[7] ),
    .A2(\sar_result[7] ),
    .Z(_282_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _592_ (
    .A1(_280_),
    .A2(_282_),
    .ZN(_283_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _593_ (
    .A1(\offset[4] ),
    .A2(\sar_result[4] ),
    .ZN(_284_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _594_ (
    .A1(\offset[4] ),
    .A2(_110_),
    .Z(_285_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _595_ (
    .A1(\offset[5] ),
    .A2(\sar_result[5] ),
    .ZN(_286_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _596_ (
    .A1(\offset[5] ),
    .A2(_109_),
    .Z(_287_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _597_ (
    .A1(_283_),
    .A2(_285_),
    .A3(_287_),
    .ZN(_288_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _598_ (
    .A1(\offset[7] ),
    .A2(\sar_result[7] ),
    .B(_279_),
    .ZN(_289_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _599_ (
    .A1(_281_),
    .A2(_289_),
    .ZN(_290_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _600_ (
    .A1(\offset[5] ),
    .A2(\sar_result[5] ),
    .B1(\offset[4] ),
    .B2(\sar_result[4] ),
    .ZN(_291_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _601_ (
    .A1(_286_),
    .A2(_291_),
    .Z(_292_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _602_ (
    .A1(_283_),
    .A2(_292_),
    .ZN(_293_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _603_ (
    .A1(_278_),
    .A2(_288_),
    .B(_290_),
    .C(_293_),
    .ZN(_294_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _604_ (
    .A1(\offset[8] ),
    .A2(\sar_result[8] ),
    .ZN(_295_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _605_ (
    .A1(_294_),
    .A2(_295_),
    .B(_262_),
    .ZN(_296_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _606_ (
    .A1(\offset[9] ),
    .A2(\sar_result[9] ),
    .ZN(_297_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _607_ (
    .A1(sar_valid),
    .A2(_297_),
    .ZN(_298_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _608_ (
    .A1(_261_),
    .A2(_296_),
    .B(_298_),
    .ZN(_299_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _609_ (
    .A1(\cal_result[0] ),
    .A2(sar_valid),
    .ZN(_300_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _610_ (
    .A1(_260_),
    .A2(_299_),
    .B(_300_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _611_ (
    .A1(\offset[1] ),
    .A2(\sar_result[1] ),
    .A3(_259_),
    .Z(_301_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _612_ (
    .A1(sar_valid),
    .A2(\cal_result[1] ),
    .ZN(_302_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _613_ (
    .A1(_299_),
    .A2(_301_),
    .B(_302_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _614_ (
    .A1(_267_),
    .A2(_270_),
    .Z(_303_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _615_ (
    .A1(sar_valid),
    .A2(\cal_result[2] ),
    .ZN(_304_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _616_ (
    .A1(_299_),
    .A2(_303_),
    .B(_304_),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _617_ (
    .A1(sar_valid),
    .A2(\cal_result[3] ),
    .ZN(_305_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _618_ (
    .A1(_268_),
    .A2(_270_),
    .B(_269_),
    .ZN(_306_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _619_ (
    .A1(_272_),
    .A2(_306_),
    .Z(_307_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _620_ (
    .A1(_299_),
    .A2(_307_),
    .B(_305_),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _621_ (
    .A1(_278_),
    .A2(_285_),
    .Z(_308_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _622_ (
    .A1(sar_valid),
    .A2(\cal_result[4] ),
    .ZN(_309_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _623_ (
    .A1(_299_),
    .A2(_308_),
    .B(_309_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _624_ (
    .A1(sar_valid),
    .A2(\cal_result[5] ),
    .ZN(_310_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _625_ (
    .A1(_277_),
    .A2(_285_),
    .B(_284_),
    .ZN(_311_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _626_ (
    .A1(_287_),
    .A2(_311_),
    .Z(_312_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _627_ (
    .A1(_299_),
    .A2(_312_),
    .B(_310_),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _628_ (
    .A1(_277_),
    .A2(_285_),
    .A3(_287_),
    .B(_292_),
    .ZN(_313_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _629_ (
    .A1(_280_),
    .A2(_313_),
    .Z(_314_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _630_ (
    .A1(_261_),
    .A2(_296_),
    .B(_298_),
    .C(_314_),
    .ZN(_315_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _631_ (
    .A1(sar_valid),
    .A2(\cal_result[6] ),
    .ZN(_316_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _632_ (
    .A1(_315_),
    .A2(_316_),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _633_ (
    .A1(sar_valid),
    .A2(\cal_result[7] ),
    .ZN(_317_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _634_ (
    .A1(_280_),
    .A2(_313_),
    .B(_279_),
    .ZN(_318_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _635_ (
    .A1(_282_),
    .A2(_318_),
    .Z(_319_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _636_ (
    .A1(_299_),
    .A2(_319_),
    .B(_317_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _637_ (
    .A1(\offset[8] ),
    .A2(\sar_result[8] ),
    .A3(_294_),
    .Z(_320_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _638_ (
    .A1(sar_valid),
    .A2(\cal_result[8] ),
    .ZN(_321_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _639_ (
    .A1(_299_),
    .A2(_320_),
    .B(_321_),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _640_ (
    .A1(sar_valid),
    .A2(\cal_result[9] ),
    .ZN(_322_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _641_ (
    .A1(_261_),
    .A2(_296_),
    .ZN(_323_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _642_ (
    .A1(sar_valid),
    .A2(_323_),
    .B(_322_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _643_ (
    .I0(\offset[0] ),
    .I1(\u_spi.mosi_reg[0] ),
    .S(_132_),
    .Z(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _644_ (
    .I0(\offset[1] ),
    .I1(\u_spi.mosi_reg[1] ),
    .S(_132_),
    .Z(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _645_ (
    .I0(\offset[2] ),
    .I1(\u_spi.mosi_reg[2] ),
    .S(_132_),
    .Z(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _646_ (
    .I0(\offset[3] ),
    .I1(\u_spi.mosi_reg[3] ),
    .S(_132_),
    .Z(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _647_ (
    .I0(\offset[4] ),
    .I1(\u_spi.mosi_reg[4] ),
    .S(_132_),
    .Z(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _648_ (
    .I0(\offset[5] ),
    .I1(\u_spi.mosi_reg[5] ),
    .S(_132_),
    .Z(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _649_ (
    .CLK(clk),
    .D(sar_valid),
    .Q(cal_valid),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _650_ (
    .CLK(cal_valid),
    .D(\cal_result[0] ),
    .Q(\u_spi.data_latch[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _651_ (
    .CLK(cal_valid),
    .D(\cal_result[1] ),
    .Q(\u_spi.data_latch[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _652_ (
    .CLK(cal_valid),
    .D(\cal_result[2] ),
    .Q(\u_spi.data_latch[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _653_ (
    .CLK(cal_valid),
    .D(\cal_result[3] ),
    .Q(\u_spi.data_latch[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _654_ (
    .CLK(cal_valid),
    .D(\cal_result[4] ),
    .Q(\u_spi.data_latch[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _655_ (
    .CLK(cal_valid),
    .D(\cal_result[5] ),
    .Q(\u_spi.data_latch[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _656_ (
    .CLK(cal_valid),
    .D(\cal_result[6] ),
    .Q(\u_spi.data_latch[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _657_ (
    .CLK(cal_valid),
    .D(\cal_result[7] ),
    .Q(\u_spi.data_latch[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _658_ (
    .CLK(cal_valid),
    .D(\cal_result[8] ),
    .Q(\u_spi.data_latch[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _659_ (
    .CLK(cal_valid),
    .D(\cal_result[9] ),
    .Q(\u_spi.data_latch[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _660_ (
    .CLK(sclk),
    .D(cs_n),
    .Q(\u_spi.cs_n_prev )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _661_ (
    .CLK(sclk),
    .D(_027_),
    .Q(\u_spi.shift_reg[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _662_ (
    .CLK(sclk),
    .D(_028_),
    .Q(\u_spi.shift_reg[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _663_ (
    .CLK(sclk),
    .D(_029_),
    .Q(\u_spi.shift_reg[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _664_ (
    .CLK(sclk),
    .D(_030_),
    .Q(\u_spi.shift_reg[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _665_ (
    .CLK(sclk),
    .D(_031_),
    .Q(\u_spi.shift_reg[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _666_ (
    .CLK(sclk),
    .D(_032_),
    .Q(\u_spi.shift_reg[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _667_ (
    .CLK(sclk),
    .D(_033_),
    .Q(\u_spi.shift_reg[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _668_ (
    .CLK(sclk),
    .D(_034_),
    .Q(\u_spi.shift_reg[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _669_ (
    .CLK(sclk),
    .D(_035_),
    .Q(\u_spi.shift_reg[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _670_ (
    .CLK(sclk),
    .D(_036_),
    .Q(\u_spi.shift_reg[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _671_ (
    .CLK(clk),
    .D(_037_),
    .Q(bp0),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _672_ (
    .CLK(clk),
    .D(_038_),
    .Q(bp1),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _673_ (
    .CLK(clk),
    .D(_039_),
    .Q(bp2),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _674_ (
    .CLK(clk),
    .D(_040_),
    .Q(bp3),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _675_ (
    .CLK(clk),
    .D(_041_),
    .Q(bp4),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _676_ (
    .CLK(clk),
    .D(_042_),
    .Q(bp5),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _677_ (
    .CLK(clk),
    .D(_043_),
    .Q(bp6),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _678_ (
    .CLK(clk),
    .D(_044_),
    .Q(bp7),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _679_ (
    .CLK(clk),
    .D(_045_),
    .Q(bp8),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _680_ (
    .CLK(clk),
    .D(_046_),
    .Q(bp9),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _681_ (
    .CLK(clk),
    .D(_047_),
    .Q(bn0),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _682_ (
    .CLK(clk),
    .D(_048_),
    .Q(bn1),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _683_ (
    .CLK(clk),
    .D(_049_),
    .Q(bn2),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _684_ (
    .CLK(clk),
    .D(_050_),
    .Q(bn3),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _685_ (
    .CLK(clk),
    .D(_051_),
    .Q(bn4),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _686_ (
    .CLK(clk),
    .D(_052_),
    .Q(bn5),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _687_ (
    .CLK(clk),
    .D(_053_),
    .Q(bn6),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _688_ (
    .CLK(clk),
    .D(_054_),
    .Q(bn7),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _689_ (
    .CLK(clk),
    .D(_055_),
    .Q(bn8),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _690_ (
    .CLK(clk),
    .D(_056_),
    .Q(bn9),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _691_ (
    .CLK(clk),
    .D(_057_),
    .Q(\sar_result[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _692_ (
    .CLK(clk),
    .D(_058_),
    .Q(\sar_result[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _693_ (
    .CLK(clk),
    .D(_059_),
    .Q(\sar_result[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _694_ (
    .CLK(clk),
    .D(_060_),
    .Q(\sar_result[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _695_ (
    .CLK(clk),
    .D(_061_),
    .Q(\sar_result[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _696_ (
    .CLK(clk),
    .D(_062_),
    .Q(\sar_result[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _697_ (
    .CLK(clk),
    .D(_063_),
    .Q(\sar_result[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _698_ (
    .CLK(clk),
    .D(_064_),
    .Q(\sar_result[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _699_ (
    .CLK(clk),
    .D(_065_),
    .Q(\sar_result[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _700_ (
    .CLK(clk),
    .D(_066_),
    .Q(\sar_result[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _701_ (
    .CLK(clk),
    .D(_067_),
    .Q(\u_sar.bit_idx[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _702_ (
    .CLK(clk),
    .D(_068_),
    .Q(\u_sar.bit_idx[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _703_ (
    .CLK(clk),
    .D(_069_),
    .Q(\u_sar.bit_idx[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _704_ (
    .CLK(clk),
    .D(_070_),
    .Q(\u_sar.bit_idx[3] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _705_ (
    .CLK(clk),
    .D(_071_),
    .Q(\u_sar.count[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _706_ (
    .CLK(clk),
    .D(_072_),
    .Q(\u_sar.count[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _707_ (
    .CLK(clk),
    .D(_073_),
    .Q(\u_sar.count[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _708_ (
    .CLK(clk),
    .D(_074_),
    .Q(\u_sar.count[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _709_ (
    .CLK(clk),
    .D(_075_),
    .Q(\u_sar.count[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _710_ (
    .CLK(clk),
    .D(_076_),
    .Q(\u_sar.count[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _711_ (
    .CLK(clk),
    .D(_077_),
    .Q(\u_sar.count[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _712_ (
    .CLK(clk),
    .D(_078_),
    .Q(\u_sar.count[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _713_ (
    .CLK(clk),
    .D(_079_),
    .Q(\cal_result[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _714_ (
    .CLK(clk),
    .D(_080_),
    .Q(\cal_result[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _715_ (
    .CLK(clk),
    .D(_081_),
    .Q(\cal_result[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _716_ (
    .CLK(clk),
    .D(_082_),
    .Q(\cal_result[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _717_ (
    .CLK(clk),
    .D(_083_),
    .Q(\cal_result[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _718_ (
    .CLK(clk),
    .D(_084_),
    .Q(\cal_result[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _719_ (
    .CLK(clk),
    .D(_085_),
    .Q(\cal_result[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _720_ (
    .CLK(clk),
    .D(_086_),
    .Q(\cal_result[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _721_ (
    .CLK(clk),
    .D(_087_),
    .Q(\cal_result[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _722_ (
    .CLK(clk),
    .D(_088_),
    .Q(\cal_result[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _723_ (
    .CLK(sclk),
    .D(_089_),
    .Q(\offset[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _724_ (
    .CLK(sclk),
    .D(_090_),
    .Q(\offset[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _725_ (
    .CLK(sclk),
    .D(_091_),
    .Q(\offset[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _726_ (
    .CLK(sclk),
    .D(_092_),
    .Q(\offset[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _727_ (
    .CLK(sclk),
    .D(_093_),
    .Q(\offset[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _728_ (
    .CLK(sclk),
    .D(_094_),
    .Q(\offset[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _729_ (
    .CLK(sclk),
    .D(_005_),
    .Q(\offset[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _730_ (
    .CLK(sclk),
    .D(_006_),
    .Q(\offset[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _731_ (
    .CLK(sclk),
    .D(_007_),
    .Q(\offset[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _732_ (
    .CLK(sclk),
    .D(_008_),
    .Q(\offset[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _733_ (
    .CLK(sclk),
    .D(_009_),
    .Q(\u_spi.mosi_reg[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _734_ (
    .CLK(sclk),
    .D(_010_),
    .Q(\u_spi.mosi_reg[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _735_ (
    .CLK(sclk),
    .D(_011_),
    .Q(\u_spi.mosi_reg[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _736_ (
    .CLK(sclk),
    .D(_012_),
    .Q(\u_spi.mosi_reg[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _737_ (
    .CLK(sclk),
    .D(_013_),
    .Q(\u_spi.mosi_reg[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _738_ (
    .CLK(sclk),
    .D(_014_),
    .Q(\u_spi.mosi_reg[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _739_ (
    .CLK(sclk),
    .D(_015_),
    .Q(\u_spi.mosi_reg[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _740_ (
    .CLK(sclk),
    .D(_016_),
    .Q(\u_spi.mosi_reg[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _741_ (
    .CLK(sclk),
    .D(_017_),
    .Q(\u_spi.mosi_reg[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _742_ (
    .CLK(sclk),
    .D(_018_),
    .Q(\u_spi.mosi_reg[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _743_ (
    .CLK(sclk),
    .D(_019_),
    .Q(\u_spi.bit_cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _744_ (
    .CLK(sclk),
    .D(_020_),
    .Q(\u_spi.bit_cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _745_ (
    .CLK(sclk),
    .D(_021_),
    .Q(\u_spi.bit_cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _746_ (
    .CLK(sclk),
    .D(_022_),
    .Q(\u_spi.bit_cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _747_ (
    .CLK(sclk),
    .D(_023_),
    .Q(\u_spi.bit_cnt[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _748_ (
    .CLK(sclk),
    .D(_024_),
    .Q(\u_spi.bit_cnt[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _749_ (
    .CLK(sclk),
    .D(_025_),
    .Q(\u_spi.bit_cnt[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _750_ (
    .CLK(sclk),
    .D(_026_),
    .Q(\u_spi.bit_cnt[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _751_ (
    .CLK(clk),
    .D(_002_),
    .Q(\u_sar.state[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _752_ (
    .CLK(clk),
    .D(\u_sar.state[5] ),
    .Q(\u_sar.state[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _753_ (
    .CLK(clk),
    .D(_003_),
    .Q(\u_sar.state[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _754_ (
    .CLK(clk),
    .D(_004_),
    .Q(\u_sar.state[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _755_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_sar.state[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _756_ (
    .CLK(clk),
    .D(_001_),
    .Q(\u_sar.state[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _757_ (
    .CLK(clk),
    .D(\u_sar.state[4] ),
    .Q(sar_valid),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _758_ (
    .ZN(bist_en)
  );
endmodule
