/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module digital_wrapper(clk, rst_n, start, comp_in, sclk, cs_n, mosi, miso, bp9, bp8, bp7, bp6, bp5, bp4, bp3, bp2, bp1, bp0, bn9, bn8, bn7
, bn6, bn5, bn4, bn3, bn2, bn1, bn0, bist_en);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input comp_in;
  wire comp_in;
  input sclk;
  wire sclk;
  input cs_n;
  wire cs_n;
  input mosi;
  wire mosi;
  output miso;
  wire miso;
  output bp9;
  wire bp9;
  output bp8;
  wire bp8;
  output bp7;
  wire bp7;
  output bp6;
  wire bp6;
  output bp5;
  wire bp5;
  output bp4;
  wire bp4;
  output bp3;
  wire bp3;
  output bp2;
  wire bp2;
  output bp1;
  wire bp1;
  output bp0;
  wire bp0;
  output bn9;
  wire bn9;
  output bn8;
  wire bn8;
  output bn7;
  wire bn7;
  output bn6;
  wire bn6;
  output bn5;
  wire bn5;
  output bn4;
  wire bn4;
  output bn3;
  wire bn3;
  output bn2;
  wire bn2;
  output bn1;
  wire bn1;
  output bn0;
  wire bn0;
  output bist_en;
  wire bist_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire \u_sar.bit_idx[0] ;
  wire \u_sar.bit_idx[1] ;
  wire \u_sar.bit_idx[2] ;
  wire \u_sar.bit_idx[3] ;
  wire \u_sar.count[0] ;
  wire \u_sar.count[1] ;
  wire \u_sar.count[2] ;
  wire \u_sar.count[3] ;
  wire \u_sar.count[4] ;
  wire \u_sar.count[5] ;
  wire \u_sar.count[6] ;
  wire \u_sar.count[7] ;
  wire \u_sar.state[0] ;
  wire \u_sar.state[1] ;
  wire \u_sar.state[2] ;
  wire \u_sar.state[3] ;
  wire \u_sar.state[4] ;
  wire \u_sar.state[5] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _151_ (
    .I(\u_sar.state[1] ),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _152_ (
    .I(\u_sar.bit_idx[0] ),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _153_ (
    .I(\u_sar.bit_idx[1] ),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _154_ (
    .I(\u_sar.bit_idx[3] ),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _155_ (
    .I(\u_sar.bit_idx[2] ),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _156_ (
    .I(\u_sar.state[0] ),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _157_ (
    .I(start),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _158_ (
    .I(\u_sar.state[2] ),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _159_ (
    .I(\u_sar.count[0] ),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _160_ (
    .I(\u_sar.state[4] ),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _161_ (
    .I(\u_sar.count[3] ),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _162_ (
    .I(\u_sar.count[6] ),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _163_ (
    .I(bn0),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _164_ (
    .I(bn1),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _165_ (
    .I(bn2),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _166_ (
    .I(bn3),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _167_ (
    .I(bn4),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _168_ (
    .I(bn5),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _169_ (
    .I(bn6),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _170_ (
    .I(bn7),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _171_ (
    .I(bn8),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _172_ (
    .I(bn9),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _173_ (
    .I(bp0),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _174_ (
    .I(bp1),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _175_ (
    .I(bp2),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _176_ (
    .I(bp3),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _177_ (
    .I(bp4),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _178_ (
    .I(bp5),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _179_ (
    .I(bp6),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _180_ (
    .I(bp7),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _181_ (
    .I(bp8),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _182_ (
    .I(bp9),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _183_ (
    .A1(\u_sar.count[4] ),
    .A2(\u_sar.count[5] ),
    .A3(\u_sar.count[6] ),
    .A4(\u_sar.count[7] ),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _184_ (
    .A1(\u_sar.count[4] ),
    .A2(\u_sar.count[5] ),
    .A3(\u_sar.count[6] ),
    .A4(\u_sar.count[7] ),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _185_ (
    .A1(\u_sar.count[2] ),
    .A2(\u_sar.count[3] ),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _186_ (
    .A1(\u_sar.count[2] ),
    .A2(\u_sar.count[3] ),
    .Z(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _187_ (
    .A1(\u_sar.count[1] ),
    .A2(_136_),
    .A3(_046_),
    .A4(_048_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _188_ (
    .A1(_135_),
    .A2(_050_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _189_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _190_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _191_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .Z(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _192_ (
    .A1(_128_),
    .A2(_053_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _193_ (
    .A1(\u_sar.count[1] ),
    .A2(\u_sar.count[0] ),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _194_ (
    .I(_054_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _195_ (
    .A1(_047_),
    .A2(_049_),
    .A3(_054_),
    .B(\u_sar.state[3] ),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _196_ (
    .A1(\u_sar.state[0] ),
    .A2(start),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _197_ (
    .A1(_056_),
    .A2(_057_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _198_ (
    .A1(\u_sar.state[3] ),
    .A2(_046_),
    .A3(_048_),
    .A4(_055_),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _199_ (
    .A1(\u_sar.state[2] ),
    .A2(_050_),
    .B1(_053_),
    .B2(\u_sar.state[1] ),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _200_ (
    .A1(_058_),
    .A2(_059_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _201_ (
    .A1(_133_),
    .A2(start),
    .B(_137_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _202_ (
    .A1(\u_sar.state[0] ),
    .A2(_134_),
    .B1(_052_),
    .B2(\u_sar.state[1] ),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _203_ (
    .A1(_128_),
    .A2(_133_),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _204_ (
    .A1(\u_sar.state[1] ),
    .A2(\u_sar.state[0] ),
    .A3(\u_sar.state[3] ),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _205_ (
    .A1(\u_sar.state[0] ),
    .A2(_134_),
    .B1(_052_),
    .B2(\u_sar.state[1] ),
    .C(_062_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _206_ (
    .A1(\u_sar.state[1] ),
    .A2(comp_in),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _207_ (
    .A1(_128_),
    .A2(_063_),
    .Z(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _208_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(_130_),
    .A3(\u_sar.bit_idx[3] ),
    .A4(_132_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _209_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_066_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _210_ (
    .A1(_042_),
    .A2(_067_),
    .B(_065_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _211_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _212_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_132_),
    .A3(_068_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _213_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_069_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _214_ (
    .A1(_043_),
    .A2(_070_),
    .B(_065_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _215_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[2] ),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _216_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_063_),
    .A3(_064_),
    .A4(_071_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _217_ (
    .A1(_044_),
    .A2(_072_),
    .B(_065_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _218_ (
    .A1(_129_),
    .A2(\u_sar.bit_idx[1] ),
    .A3(_131_),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _219_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_073_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _220_ (
    .A1(_045_),
    .A2(_074_),
    .B(_065_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _221_ (
    .A1(_140_),
    .A2(_065_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _222_ (
    .A1(_128_),
    .A2(comp_in),
    .Z(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _223_ (
    .A1(_129_),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _224_ (
    .A1(_063_),
    .A2(_075_),
    .A3(_076_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _225_ (
    .A1(_141_),
    .A2(_077_),
    .B(_065_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _226_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(_130_),
    .A3(\u_sar.bit_idx[3] ),
    .A4(\u_sar.bit_idx[2] ),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _227_ (
    .A1(_063_),
    .A2(_075_),
    .A3(_078_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _228_ (
    .A1(_142_),
    .A2(_079_),
    .B(_065_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _229_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(\u_sar.bit_idx[2] ),
    .A3(_068_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _230_ (
    .A1(_063_),
    .A2(_075_),
    .A3(_080_),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _231_ (
    .A1(_143_),
    .A2(_081_),
    .B(_065_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _232_ (
    .A1(_131_),
    .A2(\u_sar.bit_idx[2] ),
    .A3(_051_),
    .Z(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _233_ (
    .A1(_063_),
    .A2(_075_),
    .A3(_082_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _234_ (
    .A1(_144_),
    .A2(_083_),
    .B(_065_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _235_ (
    .A1(_129_),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[3] ),
    .A4(_132_),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _236_ (
    .A1(_063_),
    .A2(_075_),
    .A3(_084_),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _237_ (
    .A1(_145_),
    .A2(_085_),
    .B(_065_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _238_ (
    .A1(_063_),
    .A2(_066_),
    .A3(_075_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _239_ (
    .A1(_146_),
    .A2(_086_),
    .B(_065_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _240_ (
    .A1(_063_),
    .A2(_069_),
    .A3(_075_),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _241_ (
    .A1(_147_),
    .A2(_087_),
    .B(_065_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _242_ (
    .A1(\u_sar.bit_idx[3] ),
    .A2(_063_),
    .A3(_071_),
    .A4(_075_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _243_ (
    .A1(_148_),
    .A2(_088_),
    .B(_065_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _244_ (
    .A1(_063_),
    .A2(_073_),
    .A3(_075_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _245_ (
    .A1(_149_),
    .A2(_089_),
    .B(_065_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _246_ (
    .A1(_060_),
    .A2(_061_),
    .Z(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _247_ (
    .A1(_133_),
    .A2(start),
    .B(_053_),
    .C(\u_sar.state[1] ),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _248_ (
    .I0(_090_),
    .I1(_091_),
    .S(\u_sar.bit_idx[0] ),
    .Z(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _249_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .Z(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _250_ (
    .A1(_130_),
    .A2(_090_),
    .B1(_091_),
    .B2(_092_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _251_ (
    .A1(_051_),
    .A2(_091_),
    .B(_061_),
    .C(_060_),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _252_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .A3(_091_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _253_ (
    .A1(\u_sar.bit_idx[0] ),
    .A2(\u_sar.bit_idx[1] ),
    .A3(\u_sar.bit_idx[2] ),
    .A4(_091_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _254_ (
    .I0(_093_),
    .I1(_094_),
    .S(_132_),
    .Z(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _255_ (
    .A1(\u_sar.state[1] ),
    .A2(_057_),
    .B1(_095_),
    .B2(_131_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _256_ (
    .A1(\u_sar.state[3] ),
    .A2(\u_sar.state[2] ),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _257_ (
    .A1(\u_sar.state[3] ),
    .A2(\u_sar.state[2] ),
    .Z(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _258_ (
    .A1(\u_sar.state[1] ),
    .A2(\u_sar.state[0] ),
    .A3(\u_sar.state[3] ),
    .A4(\u_sar.state[2] ),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _259_ (
    .A1(\u_sar.state[0] ),
    .A2(_134_),
    .B1(_052_),
    .B2(\u_sar.state[1] ),
    .C(_098_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _260_ (
    .A1(_133_),
    .A2(start),
    .B1(_053_),
    .B2(_128_),
    .C(_097_),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _261_ (
    .A1(\u_sar.count[0] ),
    .A2(_096_),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _262_ (
    .A1(\u_sar.state[3] ),
    .A2(_050_),
    .B(_099_),
    .C(_101_),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _263_ (
    .A1(_136_),
    .A2(_099_),
    .B(_102_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _264_ (
    .A1(\u_sar.count[0] ),
    .A2(_099_),
    .B(\u_sar.count[1] ),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _265_ (
    .A1(\u_sar.state[3] ),
    .A2(_050_),
    .B(_054_),
    .C(_097_),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _266_ (
    .A1(_099_),
    .A2(_104_),
    .B(_103_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _267_ (
    .A1(_055_),
    .A2(_099_),
    .B(\u_sar.count[2] ),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _268_ (
    .A1(\u_sar.count[2] ),
    .A2(_055_),
    .A3(_099_),
    .Z(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _269_ (
    .A1(\u_sar.count[2] ),
    .A2(_055_),
    .A3(_099_),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _270_ (
    .A1(_135_),
    .A2(_056_),
    .A3(_099_),
    .Z(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _271_ (
    .A1(_105_),
    .A2(_106_),
    .A3(_108_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _272_ (
    .A1(\u_sar.count[1] ),
    .A2(\u_sar.count[0] ),
    .A3(\u_sar.count[2] ),
    .A4(\u_sar.count[3] ),
    .Z(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _273_ (
    .A1(\u_sar.count[1] ),
    .A2(\u_sar.count[0] ),
    .A3(\u_sar.count[2] ),
    .A4(\u_sar.count[3] ),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _274_ (
    .A1(_097_),
    .A2(_110_),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _275_ (
    .A1(_138_),
    .A2(_107_),
    .B1(_111_),
    .B2(_099_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _276_ (
    .A1(\u_sar.count[4] ),
    .A2(_109_),
    .Z(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _277_ (
    .A1(\u_sar.count[4] ),
    .A2(_109_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _278_ (
    .A1(_097_),
    .A2(_113_),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _279_ (
    .A1(_096_),
    .A2(_112_),
    .B(_099_),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _280_ (
    .A1(_099_),
    .A2(_109_),
    .B(\u_sar.count[4] ),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _281_ (
    .A1(_099_),
    .A2(_114_),
    .B(_116_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _282_ (
    .A1(_100_),
    .A2(_113_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _283_ (
    .I0(_117_),
    .I1(_115_),
    .S(\u_sar.count[5] ),
    .Z(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _284_ (
    .A1(\u_sar.count[4] ),
    .A2(\u_sar.count[5] ),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _285_ (
    .A1(_139_),
    .A2(_110_),
    .A3(_118_),
    .B(_097_),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _286_ (
    .A1(_099_),
    .A2(_119_),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _287_ (
    .A1(\u_sar.count[5] ),
    .A2(_099_),
    .A3(_112_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _288_ (
    .A1(_099_),
    .A2(_119_),
    .B1(_121_),
    .B2(_139_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _289_ (
    .A1(_139_),
    .A2(_100_),
    .A3(_110_),
    .A4(_118_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _290_ (
    .I0(_122_),
    .I1(_120_),
    .S(\u_sar.count[7] ),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _291_ (
    .A1(_150_),
    .A2(_065_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _292_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_076_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _293_ (
    .A1(_037_),
    .A2(_123_),
    .B(_065_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _294_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_078_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _295_ (
    .A1(_038_),
    .A2(_124_),
    .B(_065_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _296_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_080_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _297_ (
    .A1(_039_),
    .A2(_125_),
    .B(_065_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _298_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_082_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _299_ (
    .A1(_040_),
    .A2(_126_),
    .B(_065_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _300_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_084_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _301_ (
    .A1(_041_),
    .A2(_127_),
    .B(_065_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _302_ (
    .CLK(clk),
    .D(_031_),
    .Q(bp0),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _303_ (
    .CLK(clk),
    .D(_032_),
    .Q(bp1),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _304_ (
    .CLK(clk),
    .D(_033_),
    .Q(bp2),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _305_ (
    .CLK(clk),
    .D(_034_),
    .Q(bp3),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _306_ (
    .CLK(clk),
    .D(_035_),
    .Q(bp4),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _307_ (
    .CLK(clk),
    .D(_036_),
    .Q(bp5),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _308_ (
    .CLK(clk),
    .D(_005_),
    .Q(bp6),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _309_ (
    .CLK(clk),
    .D(_006_),
    .Q(bp7),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _310_ (
    .CLK(clk),
    .D(_007_),
    .Q(bp8),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _311_ (
    .CLK(clk),
    .D(_008_),
    .Q(bp9),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _312_ (
    .CLK(clk),
    .D(_009_),
    .Q(bn0),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _313_ (
    .CLK(clk),
    .D(_010_),
    .Q(bn1),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _314_ (
    .CLK(clk),
    .D(_011_),
    .Q(bn2),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _315_ (
    .CLK(clk),
    .D(_012_),
    .Q(bn3),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _316_ (
    .CLK(clk),
    .D(_013_),
    .Q(bn4),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _317_ (
    .CLK(clk),
    .D(_014_),
    .Q(bn5),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _318_ (
    .CLK(clk),
    .D(_015_),
    .Q(bn6),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _319_ (
    .CLK(clk),
    .D(_016_),
    .Q(bn7),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _320_ (
    .CLK(clk),
    .D(_017_),
    .Q(bn8),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _321_ (
    .CLK(clk),
    .D(_018_),
    .Q(bn9),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _322_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_sar.bit_idx[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _323_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_sar.bit_idx[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _324_ (
    .CLK(clk),
    .D(_021_),
    .Q(\u_sar.bit_idx[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _325_ (
    .CLK(clk),
    .D(_022_),
    .Q(\u_sar.bit_idx[3] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _326_ (
    .CLK(clk),
    .D(_023_),
    .Q(\u_sar.count[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _327_ (
    .CLK(clk),
    .D(_024_),
    .Q(\u_sar.count[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _328_ (
    .CLK(clk),
    .D(_025_),
    .Q(\u_sar.count[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _329_ (
    .CLK(clk),
    .D(_026_),
    .Q(\u_sar.count[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _330_ (
    .CLK(clk),
    .D(_027_),
    .Q(\u_sar.count[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _331_ (
    .CLK(clk),
    .D(_028_),
    .Q(\u_sar.count[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _332_ (
    .CLK(clk),
    .D(_029_),
    .Q(\u_sar.count[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _333_ (
    .CLK(clk),
    .D(_030_),
    .Q(\u_sar.count[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _334_ (
    .CLK(clk),
    .D(_002_),
    .Q(\u_sar.state[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _335_ (
    .CLK(clk),
    .D(\u_sar.state[5] ),
    .Q(\u_sar.state[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _336_ (
    .CLK(clk),
    .D(_003_),
    .Q(\u_sar.state[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _337_ (
    .CLK(clk),
    .D(_004_),
    .Q(\u_sar.state[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _338_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_sar.state[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _339_ (
    .CLK(clk),
    .D(_001_),
    .Q(\u_sar.state[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _340_ (
    .ZN(bist_en)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _341_ (
    .ZN(miso)
  );
endmodule
